dbt_demo:
  outputs:
    dev:
      dbname: dbt_postgres_db
      host: localhost
      pass: postgres
      port: 5432
      schema: l3_consumption
      threads: 1
      type: postgres
      user: postgres
  target: dev

